name: Test Python package on Multiple Python Versions

on:
  push:
    branches:
      - dev/mervin
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        python-version: ["3.6", "3.7", "3.7.5", "3.8", "3.8.5"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Setup Environment variables
        run: |
          cat > secret.env << 'EOF'
          # Postgres SQL settings
          export DB_USERNAME=test
          export DB_PASSWORD=test
          export DB_HOST=www.example.com
          export DB_NAME=fortweet

          # Twitter API Settings
          export TWITTER_CONSUMER_KEY="unrel"
          export TWITTER_CONSUMER_SECRET="unrel"
          export TWITTER_ACCESS_TOKEN="unrel"
          export TWITTER_ACCESS_SECRET="unrel"

          # App Settings
          export SUPER_ADMINS="jdoe@gmail.com, jdoe, jdoe"
          export STREAM_TIME=20
          export FILTERS=fortnite
          export JWT_SECRET="unrel"
          EOF
      - name: Run Environment File
        run: source ./secret.env
      - name: Test with Pytest
        run: |
          pytest
