name: Run Python Unit Tests
on:
  push:
    branches:
      - dev/mervin
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Add Config File
        run: |
          mkdir config
          touch config/settings.json
          '{"api":{"consumer_key":"unrel","consumer_secret":"unrel","access_token":"unrel-unrel","access_token_secret":"unrel"},"streaming":{"filters":["fortnite"],"stream_time":5},"super_admins":[{"username":"admin","password":"1234","email":"th3pl4gu33@gmail.com"}],"key":{"jwt_secret":"unrel"},"database":{"path":"databases/fortweets.db"}}' >> config/settings.json
      - name: Test with Pytest
        run: pytest
